### ISSUE TITLE
Mod-file installation breaks with certain compilers

### ISSUE THREAD

**Issue by aradi** [libmbd/libmbd#35]
Currently, libmbd only installs `mbd.mod` (or `MBD.mod`). Unfortunately, certain compilers (e.g. the NAG compiler) create non-self containing module files, which dynamically load other module files when parsed by the compiler. Consequently, basically all module files and not just `mbd.mod` must be present in the installation directory, in order to able to use the `mbd` module in an external program. Unfortunately, the standard does not say anything about the modfiles (it does not even requires them to be files), so such behavior is very likely standard conforming...

**Comment by jhrmnn** [comment]
Interesting! Since you are much more well-versed in CMake, do you think #36 should work?

**Comment by aradi** [comment]
Yes, this is basically how we do it currently in DFTB+ as well. As it will result in several modfiles being installed, you might also consider to install those into a fortran specific subfolder within the project specific include folder (e.g. `mbd/fmod`, `mbd/modules`, `mbd/modfiles`)

**Comment by jhrmnn** [comment]
Cool, thanks. There is only one C header file apart from those, so I think they can be safely in one folder.
