### ISSUE TITLE
Version extraction issue when doing a shallow clone

### ISSUE THREAD

**Issue by ye-luo** [libmbd/libmbd#62]
reproducer
```
git clone --depth 1 https://github.com/libmbd/libmbd
cd libmbd
mkdir build
cd build
cmake ..
```
printout
```
-- Setting version tag to  from Git
CMake Error at cmake/libMBDVersion.cmake:20 (string):
  string sub-command REGEX, mode MATCH needs at least 5 arguments total to
  command.
Call Stack (most recent call first):
  CMakeLists.txt:13 (include)
```
caused by
```
git describe --tags --dirty=.dirty
fatal: No names found, cannot describe anything.
```

**Comment by jhrmnn** [comment]
Yeah, the version information is not included in the source code, so this just can’t work. How was this handled previously in QE? Is a full clone not an option?

**Comment by ye-luo** [comment]
82005cbb65bdf5d32ca021848eec8f19da956a77 was used and it doesn't have the version extraction part. I believe once you make a tag, and shallow clone hits that clone, version extraction will work.

**Comment by jhrmnn** [comment]
Ok, I will then make a release, I don't want to complicate things by having non-release tags. I'll do it when we have the compiler workaround, or you tell me it's not needed.

**Comment by ye-luo** [comment]
> Ok, I will then make a release, I don't want to complicate things by having non-release tags. I'll do it when we have the compiler workaround, or you tell me it's not needed.

Since QE not really need the C API. So I just set ENABLE_C_API to OFF as a workaround. So please create a tag for the current develop and I should be able to conclude QE side of version update.

**Comment by jhrmnn** [comment]
I’ve tagged the current master as 0.13.0, let me know if it works.

**Comment by ye-luo** [comment]
> I’ve tagged the current master as 0.13.0, let me know if it works.

Seems all good on the QE side.

**Comment by ye-luo** [comment]
I have to reopen this issue. I noticed the issue can reappear in two scenarios.
1. when QE users don't have internet and use shallow clone to access libmbd
2. Once the HEAd of libmbd repo moves to a commit newer than what QE uses. The tag won't show up and the CMake failure will occur.

One solution can image is when no tag is found, use the commit hash.
